layout ( row_major, std140 ) uniform _Intrinsic_Other
{
    mat4x4 _INTRINSIC_TRANSFORM_VIEW;
    mat4x4 _INTRINSIC_TRANSFORM_PROJECTION;

    float _INTRINSIC_PROJECTION_NEAR;
    float _INTRINSIC_PROJECTION_FAR;
    float _INTRINSIC_PROJECTION_ASPECT_RATIO;
    float _INTRINSIC_PROJECTION_VERTICAL_FIELD_OF_VIEW;
};
